package me.yluo.ruisiapp.api.entity;

public class Thread {

    public String tid;
    public String fid;
    public String posttableid;
    public String typeid;
    public String sortid;
    public String readperm;
    public String price;
    public String author;
    public String authorid;
    public String subject;
    public String dateline;
    public String lastpost;
    public String lastposter;
    public String views;
    public String replies;
    public String displayorder;
    public String highlight;
    public String digest;
    public String rate;
    public String special;
    public String attachment;
    public String moderated;
    public String closed;
    public String stickreply;
    public String recommends;
    public String recommend_add;
    public String recommend_sub;
    public String heats;
    public String status;
    public String isgroup;
    public String favtimes;
    public String sharetimes;
    public String stamp;
    public String icon;
    public String pushedaid;
    public String cover;
    public String replycredit;
    public String relatebytag;
    public String maxposition;
    public String bgcolor;
    public String comments;
    public String hidden;
    public String threadtable;
    public String threadtableid;
    public String posttable;
    public String addviews;
    public String allreplies;
    public String is_archived;
    public String archiveid;
    public String subjectenc;
    public String short_subject;
    public String recommend;
}